<h1>MGD(Mini Batch Gradient Desent)</h1>

아래는 변수 설정은 BGD와 동일 

In [27]:
import numpy as np

# 가상의 데이터 생성
np.random.seed(42)    

X = 2 * np.random.rand(100, 1) 
y = 4 + 3 * X + np.random.randn(100, 1) 

X_b = np.c_[np.ones((100, 1)), X]

| lr | n_epochs | m | batch_size |
|-----|--------------|---|----|
|학습률| 반복횟수(몇 번의 epoch이 진행될 것인지 의미) | 학습에 사용된 샘플 수| 배치 사이즈 |

In [28]:
# 초기값 설정
lr = 0.1
n_epochs = 1000
m = 100 
batch_size = 10

theta_mgd는 mgd가 찾고자하는 변수이다. 현재 2개의 변수를 찾아야 하기에 랜덤한 숫자로 만들어지 2 x 1 배열을 생성한다.

In [29]:
theta_mgd = np.random.randn(2, 1)
theta_mgd_path = []

mgd의 경우 한번의 iteration 마다 샘플을 여러개의 mini batch로 나눈 뒤 각각을 계산한다.

shuffled_indices는 np.random.permutation(m)를 통해 변수의 갯수와 동일한 수를 무작위로 나열한다.
이후 X_b_shuffled, y_shuffled 변수에 X_b와 y를 [shuffled_indices]에 맞게 데이터 셔플링을 한 배열을 저장한다.

이후 batch size에 맞게 계산을 한다. 미니 배치로 한번 계산할 때마다 gradient를 계산한다. 이 코드에서는 100개의 데이터를 10개로 나눴기에 한번의 iteration 동안 10번의 gradient 조정이 일어난다.

In [30]:
for n_epoch in range(n_epochs):
    i = np.random.randint(m)
    shuffled_indices = np.random.permutation(m)
    X_b_shuffled = X_b[shuffled_indices]
    y_shuffled = y[shuffled_indices]
    xi = X_b_shuffled[i:i+batch_size]
    yi = y_shuffled[i:i+batch_size]
    gradients = 2/batch_size * xi.T.dot(xi.dot(theta_mgd) - yi)
    theta_mgd = theta_mgd - lr * gradients
    theta_mgd_path.append(theta_mgd)

theta_mgd_path = np.array(theta_mgd_path)

[[[1.19661328]
  [2.83618791]]

 [[1.72475134]
  [3.22747892]]

 [[2.07559728]
  [3.57596146]]

 ...

 [[4.27933078]
  [2.86389747]]

 [[4.18641473]
  [2.72822743]]

 [[4.24302491]
  [2.8040117 ]]]
