<h1>SGD</h1>

아래는 변수 설정은 BGD와 동일 

In [14]:
import numpy as np

# 가상의 데이터 생성
np.random.seed(42)    

X = 2 * np.random.rand(100, 1) 
y = 4 + 3 * X + np.random.randn(100, 1) 

X_b = np.c_[np.ones((100, 1)), X]

| lr | n_epochs | m |
|-----|--------------|---|
|학습률| 전체 데이터를 몇 번의 볼것인지 | 학습에 사용된 샘플 수|



In [16]:
# 초기값 설정
lr = 0.1
n_epochs = 1000
m = 100

theta_sgd는 sgd가 찾고자하는 변수이다. 현재 2개의 변수를 찾아야 하기에 랜덤한 숫자로 만들어지 2 x 1 배열을 생성한다.

In [18]:
theta_sgd = np.random.randn(2, 1) 
theta_sgd_path = []

SGD의 경우는 오직 1개의 변수만을 가지고 기울기를 수정한다. 따라서 데이터의 수에 따라 기울기 갱신 횟수는 증가한다.

In [19]:
for epoch in range(n_epochs):
    random_index = np.random.randint(m)
    xi = X_b[random_index:random_index+1]
    yi = y[random_index:random_index+1]
    gradients = 2 * xi.T.dot(xi.dot(theta_sgd) - yi)
    theta_sgd = theta_sgd - lr * gradients
    theta_sgd_path.append(theta_sgd)

theta_sgd_path = np.array(theta_sgd_path)

[[[0.96804447]
  [2.43576565]]

 [[1.40013784]
  [2.74406714]]

 [[1.93673966]
  [3.30506592]]

 ...

 [[4.19145627]
  [2.73416771]]

 [[4.18978391]
  [2.73378016]]

 [[4.19000137]
  [2.73381258]]]
